apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-project
  labels:
    app: capstone-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-project
  template:
    metadata:
      labels:
        app: capstone-project
    spec:
      containers:
        - image: mtan11/capstone-project:latest
          name: capstone-project
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      restartPolicy: Always